name = "SpaceGroups"
uuid = "c9e7fe64-f4ce-462e-96f2-f923a4d16e38"
authors = ["Pavel Kalugin <pkfrance@yahoo.com> and contributors"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
