name = "SpaceGroups"
uuid = "c9e7fe64-f4ce-462e-96f2-f923a4d16e38"
authors = ["pkfrance <pkfrance@yahoo.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
